<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>

</body>

</html>
<script src="../day01/jquery-3.3.1.js"></script>
<script>
    let p = new Promise(function (res, rej) {
        // setTimeout(() => {
        //     console.log(qqq)
        // }, 2000)
        $.ajax({
            url: './1.json',
            success: function (data) {
                res(data)
            },
            error: function (err) {
                res(err)
            }
        })
    }).then(function (data) {
        console.log(1)
    }, function () {
        console.log(0)
    }).catch(() => {
        console.log(666, err)
    }).finally(() => {
        // console.log(888)     //不管成功或者失败都执行
    });
    // then catch finally 这三个方法都在Promise的原型上；
    // all  race  resolve reject 

    let p1 = new Promise(function (res, rej) {
        setTimeout(() => {
            res(111)
        }, 2000)
    }); 
    let p2 = new Promise(function (res, rej) {
        setTimeout(() => {
            rej(222)
        }, 3000)
    }); 
    let p3 = new Promise(function (res, rej) {
        setTimeout(() => {
            res(333)
        }, 4000)
    });

    //  all 所有的都成功 才会走成功的回调函数，只要有一个失败 就直接走对应的函数 不在继续往下走
    // exeutor 函数是一个听不执行的函数，then catch 里面的函数是异步执行的
    Promise.all([p1,p2,p3]).then((data)=>{
        console.log('data',data)
    },(err)=>{
        console.log('err',err)
    })
    Promise.allSettled([p1,p2,p3]).then((data)=>{
        console.log(data)
    })
    Promise.race([p1,p2,p3]).then((data)=>{
        console.log('sucess',data)
    },(err)=>{
        console.log('fail',err)
    })

    Promise.resolve(333).then((data)=>{
        console.log(data)
    })
    Promise.reject(444).then((data)=>{
        console.log(data)
    })
</script>